language: node_js

os:
  - linux
  - osx

branches:
  only:
    - master
    - final

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'

notifications:
  email:
    on_success: never
    on_failure: change
