branches:
  only:
    - master
    - final

environment:
  nodejs_version: '8.11.3'

install:
  - npm install yarn -g
  - yarn
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test
